# Generated by Django 5.0.6 on 2024-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
